name: Publish Package to npmjs

run-name: 'Publish package `${{ inputs.package }}`'

on:
  workflow_dispatch:
    inputs:
      package:
        description: Choose package to publish
        required: true
        type: choice
        options:
          - 'eslint-config-typescript'
          - 'eslint-config-typescript-next'
          - 'eslint-config-typescript-react'
          - 'eslint-config-javascript-react'
          
jobs:
  Build:
    runs-on: ubuntu-latest

    timeout-minutes: 5
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          cd ${{ inputs.package }}
          npm publish
